### ISSUE TITLE
Graph setup not saving

### ISSUE THREAD

**Issue by ghost** [RaceFlightOne/blackbox-log-viewer#1]
when changes are made to the graph setup, they are not being saved and lost after restarting the application
no matter if the default setup is edited, or a custom one
and starting as admin also wont help

maybe a localstorage or chromestorage issue?
see file pref_storage.js

**Comment by Arti3DPlayer** [comment]
@2mod could you please send the flight log ?

**Comment by ghost** [comment]
@Arti3DPlayer doesnt matter which flight log, its always been like that, incl logs from other ppl
but here you are ^^
[flightlog_2017-101-11_224330.txt](https://github.com/RaceFlightOne/blackbox-log-viewer/files/1465085/flightlog_2017-101-11_224330.txt)
[flightlog_2017-101-2_191141.txt](https://github.com/RaceFlightOne/blackbox-log-viewer/files/1465086/flightlog_2017-101-2_191141.txt)
[flightlog_2017-91-26_13219.txt](https://github.com/RaceFlightOne/blackbox-log-viewer/files/1465088/flightlog_2017-91-26_13219.txt)

**Comment by Arti3DPlayer** [comment]
@2mod will fix in next version
