### ISSUE TITLE
Craft display in 3D mode wont work

### ISSUE THREAD

**Issue by ghost** [RaceFlightOne/blackbox-log-viewer#2]
setting the craft display mode to 3D in the layout settings doesnt seem to display the craft
maybe because WebGL is missing?
2D mode seems to work though

**Comment by Arti3DPlayer** [comment]
@2mod flight log please

**Comment by ghost** [comment]
@Arti3DPlayer doesnt matter which flight log, also had some ppl missing the 3D craft on slack
could it be associated to the set default browser or chrome version? which would be firefox and comodo (instead of the original chrome)
